Calculator
LuckyAm20/Calc pull request #1
Opened 2023-10-06 20:04 UTC by LuckyAm20

2023-10-06 20:21 UTC, LuckyAm20 commented
Аптуков Михаил 5030102/10201

2023-10-08 16:21 UTC, Kauter1989 requested changes

2023-10-08 16:21 UTC, Kauter1989 commented on lab1/CMakeLists.txt
> +configure_file(${PROJECT_SOURCE_DIR}/plugins/DLL_1.dll ${PROJECT_BINARY_DIR}/plugins/DLL_1.dll COPYONLY)
этого не нужно делать, все dll только на этапе рантайма находим и подгружаем

2023-10-08 16:21 UTC, Kauter1989 commented on lab1/README.md
> +1)����������� �������� ��������� ��������� � ���������� /*-+, � ����� ������������ () � ����������
??? нечитаемо

2023-10-08 16:21 UTC, Kauter1989 commented on lab1/calculator.cpp
> +        cerr << "������: " << e.what() << endl;
Нечитаемое сообщение

2023-10-08 16:21 UTC, Kauter1989 commented on lab1/plugins/DLL_1.cpp
> +	__declspec(dllexport) int op_priority = 3;
Где тут С++?

2023-10-08 16:21 UTC, Kauter1989 commented on lab1/validator.h
> +using std::map, std::vector, std::string, std::runtime_error, std::stack;
Почему using в h? Вы раскрываете эти типы в т.ч. везде, где сделано включение этого h

2023-10-08 20:21 UTC, LuckyAm20 commented on lab1/README.md
> +1)����������� �������� ��������� ��������� � ���������� /*-+, � ����� ������������ () � ����������
переписал readme

2023-10-08 20:22 UTC, LuckyAm20 commented on lab1/CMakeLists.txt
> +configure_file(${PROJECT_SOURCE_DIR}/plugins/DLL_1.dll ${PROJECT_BINARY_DIR}/plugins/DLL_1.dll COPYONLY)
добавил автоматическую подгрузку dll из папки plugins, также проверил, что проект теперь не требует пересборки при добавлении или удалении dll из plugins

2023-10-08 20:23 UTC, LuckyAm20 commented on lab1/calculator.cpp
> +        cerr << "������: " << e.what() << endl;
исправил весь русский текст на англ для корректного отображения

2023-10-08 20:24 UTC, LuckyAm20 commented on lab1/validator.h
> +using std::map, std::vector, std::string, std::runtime_error, std::stack;
убрал using чтобы не было повторного раскрытия всех типов

2023-10-08 20:29 UTC, LuckyAm20 commented on lab1/plugins/DLL_1.cpp
> +	__declspec(dllexport) int op_priority = 3;
в коде использована std::string из языка c++. Запись extern "C" позволяет обращаться к переменным и функциям по имени и не запрещает использование синтаксиса c++, недоступного в языке C.

2023-10-11 16:44 UTC, Kauter1989 requested changes

2023-10-11 16:44 UTC, Kauter1989 commented on lab1/inf_for_calc.cpp
> +            throw std::exception("Problem with opening dll");
Если первая dll оказалась фейковой, то остальные даже не будут проверены

2023-10-11 16:58 UTC, LuckyAm20 commented on lab1/inf_for_calc.cpp
> +            throw std::exception("Problem with opening dll");
исправил ошибку в коммите 52434e2e266d9e042e948caa4ab1ce7f9200c89d

2023-10-11 18:36 UTC, Kauter1989 requested changes

2023-10-11 18:36 UTC, Kauter1989 commented on lab1/CMakeLists.txt
> +  set_property(TARGET Calc PROPERTY CXX_STANDARD 20)
Зачем 20й стандарт?

2023-10-11 18:36 UTC, Kauter1989 commented on lab1/plugins/DLL_1.cpp
> +	__declspec(dllexport) int op_priority = 3;
С++ - это ООП, а не использование только string. Классы нужно спроектировать

2023-10-11 18:36 UTC, Kauter1989 commented on lab1/plugins/DLL_1.cpp
> +	__declspec(dllexport) double function(double a, double b) { if (a < 0 && b - (int)b != 0) { throw std::exception("You cannot raise a negative number to a fractional power!"); } return pow(a, b); }
Почему в If завернута конвертация типов? вы пытаетесь стандартную функцию реализовать через лишнее приведение типа, еще и в условии ветвления

2023-10-11 18:36 UTC, Kauter1989 commented on lab1/plugins/DLL_1.cpp
> +	__declspec(dllexport) string name_type() { return "op"; }
что такое "name type"? почему это string, а не enum?

2023-10-11 18:36 UTC, Kauter1989 commented on lab1/plugins/DLL_2.cpp
> +	__declspec(dllexport) double function(double a) { if (a < 0) { throw std::exception("It is impossible to extract the square root!"); } return sqrt(a); }
sqrt сам по себе exception не выбросит?

2023-10-11 18:36 UTC, Kauter1989 commented on lab1/validator.cpp
> +    std::stack<char> brackets;
Почему не unsigned char? не wchar? почему именно stack, а не vector?

2023-10-11 18:36 UTC, Kauter1989 commented on lab1/validator.cpp
> +        else if (c == ')')
Масса неструктурированных случаев, которые вы разбираете посимвольно единым полотном кода

2023-10-11 23:37 UTC, LuckyAm20 commented on lab1/CMakeLists.txt
> +  set_property(TARGET Calc PROPERTY CXX_STANDARD 20)
Создался автоматически при создании проекта, исправил на 17 в коммите 78d04df270e8500d3792fc6a6e13ea31f767e2ef

2023-10-11 23:39 UTC, LuckyAm20 commented on lab1/plugins/DLL_1.cpp
> +	__declspec(dllexport) double function(double a, double b) { if (a < 0 && b - (int)b != 0) { throw std::exception("You cannot raise a negative number to a fractional power!"); } return pow(a, b); }
убрал лишнюю часть кода в коммите 78d04df270e8500d3792fc6a6e13ea31f767e2ef

2023-10-11 23:40 UTC, LuckyAm20 commented on lab1/plugins/DLL_1.cpp
> +	__declspec(dllexport) string name_type() { return "op"; }
исправил на enum в коммите 78d04df270e8500d3792fc6a6e13ea31f767e2ef

2023-10-11 23:41 UTC, LuckyAm20 commented on lab1/plugins/DLL_2.cpp
> +	__declspec(dllexport) double function(double a) { if (a < 0) { throw std::exception("It is impossible to extract the square root!"); } return sqrt(a); }
он выводил что результат неопределен, а я хотел чтобы была описана конкретная произошедшая проблема. Убрал выброс излишнего исключения в коммите 78d04df270e8500d3792fc6a6e13ea31f767e2ef

2023-10-11 23:42 UTC, LuckyAm20 commented
в коммите 78d04df270e8500d3792fc6a6e13ea31f767e2ef была полностью переписана структура хранения информации в dll с использованием принципов ооп

2023-10-11 23:53 UTC, LuckyAm20 commented on lab1/validator.cpp
> +    std::stack<char> brackets;
исправил тип на более подходящий в коммите 6c52792ec340ff70231b716863b759d070ac6d14. В данном случае мне стек показался наиболее подходящим контейнером для хранения скобок, потому что он обеспечивает LIFO порядок операций

2023-10-12 00:19 UTC, LuckyAm20 commented
в коммите 02c5971c1858d8e63b6a277161c07d830dc99e56 в коде парсера выделены части кода в отдельные функции для улучшения читабельности

2023-10-12 01:46 UTC, LuckyAm20 commented on lab1/validator.cpp
> +        else if (c == ')')
выделил куски кода валидатора в отдельные функции, привел код в более читаемый вид(структурировал его) в коммите 0fdaa2c26da86a84a03f8ae934e31ad656a1f825

2023-10-12 18:35 UTC, Kauter1989 approved these changes

2023-10-13 01:10 UTC, merged